[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[functions]
  directory = "functions-build"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000

[build.environment]
  NODE_VERSION = "18" 