[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "ejs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000

[build.environment]
  NODE_VERSION = "18" 